"""pytest collector and item classes for Markdown console blocks."""

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

import pytest

from .parsing import parse_blocks
from .runner import (
    ConsoleCommandFailed,
    ConsoleOutputMismatch,
    ConsoleUnexpectedSuccess,
    run_command,
)

if TYPE_CHECKING:
    from collections.abc import Generator
    from pathlib import Path
    from typing import Any

    from .models import ConsoleBlock


class MarkdownFile(pytest.File):
    """pytest collector for Markdown files containing console blocks."""

    def collect(self) -> Generator[ConsoleBlockItem, None, None]:
        """Yield a ConsoleBlockItem for each testable console block."""
        source = self.path.read_text(encoding="utf-8")
        directive = self.config.getini("markdown_console_directive") or "pytest-markdown-console"
        blocks = parse_blocks(source, directive=directive)
        for idx, block in enumerate(blocks):
            if not block.commands or block.notest:
                continue
            name = f"console[{idx}]@line{block.line_number}"
            yield ConsoleBlockItem.from_parent(self, name=name, block=block)


class ConsoleBlockItem(pytest.Item):
    """pytest item representing one console block."""

    def __init__(self, *, block: ConsoleBlock, **kwargs: Any) -> None:  # noqa: ANN401
        """Initialize with the parsed ConsoleBlock."""
        super().__init__(**kwargs)
        self.block = block
        self.add_marker("markdown_console")

    def runtest(self) -> None:
        """Run all commands in the block and assert their output."""
        current = sys.platform
        if self.block.only_platforms and current not in self.block.only_platforms:
            pytest.skip(
                f"console block requires platform in {sorted(self.block.only_platforms)!r},"
                f" current platform is {current!r}",
            )
        if current in self.block.skip_platforms:
            pytest.skip(f"console block is skipped on platform {current!r}")

        base_dir = self.path.parent
        if self.block.cwd_override is not None:
            cwd_path = (base_dir / self.block.cwd_override).resolve()
            if not cwd_path.is_dir():
                msg = f"cwd path does not exist: {cwd_path}"
                raise FileNotFoundError(msg)
            cwd = str(cwd_path)
        else:
            cwd = str(base_dir)

        ini_shell = self.config.getini("markdown_console_shell") or None
        effective_shell = self.block.shell or ini_shell

        for command in self.block.commands:
            cwd = run_command(command, cwd, shell=effective_shell)

    def repr_failure(self, excinfo: pytest.ExceptionInfo[BaseException]) -> str | pytest.TerminalRepr:
        """Format a human-readable failure message."""
        if isinstance(excinfo.value, ConsoleOutputMismatch):
            e = excinfo.value
            return f"Command:  $ {e.cmd}\nExpected:\n{e.expected}\nGot:\n{e.actual}"
        if isinstance(excinfo.value, ConsoleUnexpectedSuccess):
            e = excinfo.value
            return f"Command:  $ {e.cmd}  # Error:\nExpected a non-zero exit code, but the command succeeded."
        if isinstance(excinfo.value, ConsoleCommandFailed):
            e = excinfo.value
            msg = f"Command:  $ {e.cmd}\nCommand failed with exit code {e.returncode}."
            if e.stderr:
                msg += f"\nStderr:\n{e.stderr}"
            return msg
        return super().repr_failure(excinfo)

    def reportinfo(self) -> tuple[Path, int, str]:
        """Return location info for pytest's report header."""
        return self.path, self.block.line_number - 1, f"console block @ line {self.block.line_number}"


def pytest_addoption(parser: pytest.Parser) -> None:
    """Register ini options for pytest-markdown-console."""
    parser.addini(
        "markdown_console_shell",
        help=(
            "Default shell for console blocks (pwsh, cmd, sh, bash, zsh, …). Defaults to pwsh on Windows, sh elsewhere."
        ),
        type="string",
        default=None,
    )
    parser.addini(
        "markdown_console_directive",
        help='HTML comment tag for directives (default: "pytest-markdown-console").',
        type="string",
        default="pytest-markdown-console",
    )


def pytest_configure(config: pytest.Config) -> None:
    """Register the markdown_console marker."""
    config.addinivalue_line(
        "markers",
        "markdown_console: marks tests generated by pytest-markdown-console",
    )


def pytest_collect_file(parent: pytest.Collector, file_path: Path) -> MarkdownFile | None:
    """Return a MarkdownFile collector for .md files."""
    if file_path.suffix == ".md":
        return MarkdownFile.from_parent(parent, path=file_path)
    return None
