line-length    = 120
target-version = "py312"

[lint]
select = [
    "A",    # flake8-builtins
    "ANN",  # flake8-annotations
    "ARG",  # flake8-unused-arguments
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "C4",   # flake8-comprehensions
    "C90",  # mccabe
    "COM",  # flake8-commas
    "D",    # pydocstyle
    "E",    # pycodestyle errors
    "EM",   # flake8-errmsg
    "F",    # pyflakes
    "FBT",  # flake8-boolean-trap
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "PERF", # Perflint
    "PIE",  # flake8-pie
    "PL",   # Pylint
    "PT",   # flake8-pytest-style
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "SLOT", # flake8-slots
    "TC",   # flake8-type-checking
    "TID",  # flake8-tidy-imports
    "TRY",  # tryceratops
    "PL",   # Pylint
    "RUF",  # Ruff-specific rules
    "S",    # flake8-bandit
    "UP",   # pyupgrade
]

[lint.per-file-ignores]
"tests/**" = [
    "ANN", # flake8-annotations
    "S",   # flake8-bandit
]

[lint.pydocstyle]
convention = "google"
